import html2canvas from 'html2canvas'
import type { ChatMessage } from '../adapters/base'
import { showGlobalLoading, hideGlobalLoading } from '../styles/loading'
import { type LogCallback} from '../adapters/base'
export async function generateImage(data: ChatMessage[], _config: any, addLog: LogCallback) {

  addLog("log_picStart_messgae")
  showGlobalLoading()

  await new Promise(resolve => setTimeout(resolve, 300))

  const container = document.createElement('div')
  container.style.cssText = `
    position: absolute
    top: -9999px
    left: -9999px
    width: 800px
    background: #f8fafc
    padding: 40px
    font-family: 'Segoe UI', system-ui, sans-serif
    color: #334155
    box-sizing: border-box
  `

  try {
    const dateStr = new Date().toLocaleString()
    container.innerHTML = `
    <div style="border-bottom: 2px solid #e2e8f0 padding-bottom: 20px margin-bottom: 30px display: flex justify-content: space-between align-items: flex-end">
      <div>
        <h1 style="margin: 0 font-size: 28px color: #0f172a">OmniAI</h1>
        <p style="margin: 5px 0 0 color: #64748b font-size: 14px">Total ${data.length} Items</p>
      </div>
      <div style="text-align: right color: #94a3b8 font-size: 12px">
        <div>${dateStr}</div>
        <div style="font-weight: bold color: #10b981 margin-top: 4px">Generated by OmniAI Exporter</div>
      </div>
    </div>
  `
    
    for (const msg of data) {
      const isUser = msg.role === 'user'
      const bubbleColor = isUser ? '#ffffff' : '#f0fdf4'
      const borderColor = isUser ? '#e2e8f0' : '#10b981'
      const avatar = isUser ? '👤 YOU' : '🤖 AI'

      const msgBlock = document.createElement('div')
      msgBlock.style.cssText = `
        margin-bottom: 24px
        background: ${bubbleColor}
        border: 1px solid ${borderColor}
        border-radius: 12px
        padding: 20px
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05)
      `

      const tempDiv = document.createElement('div')
      tempDiv.innerHTML = msg.html

      tempDiv.querySelectorAll('*').forEach(el => {
        const htmlEl = el as HTMLElement
        
        const isCodeBlock = htmlEl.closest('pre') || htmlEl.closest('code')

        if (!isCodeBlock) {
          htmlEl.style.color = 'inherit' 
          htmlEl.style.backgroundColor = 'transparent' 
        } else {
          if (htmlEl.tagName.toLowerCase() === 'pre') {
            htmlEl.style.backgroundColor = '#1e293b' 
            htmlEl.style.color = '#f8fafc' 
            htmlEl.style.padding = '16px'
            htmlEl.style.borderRadius = '8px'
            htmlEl.style.border = '1px solid #334155'
            
            htmlEl.style.whiteSpace = 'pre-wrap' 
            htmlEl.style.wordWrap = 'break-word' 
            htmlEl.style.wordBreak = 'break-all' 
            htmlEl.style.overflowX = 'visible'  
          }
          
        }
      })

      msgBlock.innerHTML = `
        <div style="font-weight: 800 font-size: 14px margin-bottom: 12px color: ${isUser ? '#475569' : '#10b981'}">
          ${avatar}
        </div>
        <div style="line-height: 1.6 font-size: 15px overflow-wrap: break-word">
          ${tempDiv.innerHTML}
        </div>
      `
      container.appendChild(msgBlock)
      
      await new Promise(resolve => setTimeout(resolve, 10))
    }

    document.body.appendChild(container)

    await new Promise(resolve => setTimeout(resolve, 100))


    const canvas = await html2canvas(container, {
      scale: 2, 
      useCORS: true,
      backgroundColor: '#f8fafc',
      logging: false //
    })

    const blob = await new Promise<any>((resolve) => {
      canvas.toBlob((b) => resolve(b), 'image/png')
    })

    if (!blob) {
      addLog("log_error_message", "The content may be too long and exceeds browser limits ")
    }

    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `OmniAI_Image_${Date.now()}.png`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    
    URL.revokeObjectURL(url) 

    addLog("log_success_message")
  } catch (error) {
    addLog("log_error_message", String(error))
  } finally {
    if (document.body.contains(container)) {
      document.body.removeChild(container)
    }
    hideGlobalLoading()
  }
}